CREATE TABLE TCCO_FILE
(
  FLE_KEY       VARCHAR2(100 BYTE)              NOT NULL,
  ATCH_FLE_SEQ  VARCHAR2(22 BYTE)               NOT NULL,
  FLE_TP        VARCHAR2(100 BYTE),
  FLE_PATH      VARCHAR2(100 BYTE),
  FLE_NM        VARCHAR2(1000 BYTE),
  NEW_FLE_NM    VARCHAR2(1000 BYTE),
  FLE_SZ        VARCHAR2(20 BYTE),
  INS_ID        VARCHAR2(20 BYTE),
  INS_DT        DATE,
  UPT_ID        VARCHAR2(20 BYTE),
  UPT_DT        DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE TCCO_FILE IS '첨부파일관리';

COMMENT ON COLUMN TCCO_FILE.FLE_KEY IS '첨부파일아이디';

COMMENT ON COLUMN TCCO_FILE.ATCH_FLE_SEQ IS '첨부파일순번';

COMMENT ON COLUMN TCCO_FILE.FLE_TP IS '파일유형';

COMMENT ON COLUMN TCCO_FILE.FLE_PATH IS '파일경로';

COMMENT ON COLUMN TCCO_FILE.FLE_NM IS '파일명';

COMMENT ON COLUMN TCCO_FILE.NEW_FLE_NM IS '신규파일명';

COMMENT ON COLUMN TCCO_FILE.FLE_SZ IS '파일사이즈';

COMMENT ON COLUMN TCCO_FILE.INS_ID IS '등록자';

COMMENT ON COLUMN TCCO_FILE.INS_DT IS '등록일';

COMMENT ON COLUMN TCCO_FILE.UPT_ID IS '수정자';

COMMENT ON COLUMN TCCO_FILE.UPT_DT IS '수정일';



CREATE UNIQUE INDEX PK_TCCO_FILE ON TCCO_FILE
(FLE_KEY, ATCH_FLE_SEQ)
LOGGING
NOPARALLEL;


ALTER TABLE TCCO_FILE ADD (
  CONSTRAINT PK_TCCO_FILE
  PRIMARY KEY
  (FLE_KEY, ATCH_FLE_SEQ)
  USING INDEX PK_TCCO_FILE);

