/*==============================================================
* Generated by somangLee on 2022-01-17
==============================================================*/
$(document).ready(function(){		

  // Start motion
  setTimeout(function(){
    $('body').addClass('login-start');
  }, 500);

  $('.datepicker').datepicker();
  
  // tab2
  $('ul.tab2 li').click(function(){
    var tab = $(this).attr('tab');
    if(!$(this).hasClass('current')) {
      // class 삭제
      $(this).siblings('li').removeClass('current');
      $(this).parents('ul.tab2').siblings('div.tab-content.current').removeClass('current');
      // class 추가 
      $(this).addClass('current');
      $(this).parents('ul.tab2').siblings('div[tab='  + tab + ']').addClass('current');
    }
  });
});

