/*==============================================================
* Generated by somangLee on 2022-01-06
==============================================================*/
$(document).ready(function(){

  // 버튼 클릭시 레이어팝업 오픈 (같은 파일에 있을때 적용)
  $('[modal-id]').click(layerPopup);

  // 닫기, 취소 버튼 클릭시 레이어팝업 사라짐
   $('.popup-close-btn, .foot-btn-area .btn-style3').on('click', function(){
    $(this).parents('.layer-popup').removeClass('active');
    $('html').removeClass('hidden');
  });
})

// layerPopup
function layerPopup() {
  var id = $(this).attr('modal-id');
  $('.layer-popup').removeClass('active').filter('#' + id).addClass('active');
  // tab키 눌렀을때 포커스 이동 순서 
  $(".popup-cont").attr("tabindex", 0).focus();
  // 레이어팝업 오픈시 html 스크롤 제어
  $('html').addClass('hidden');
}
