/*==============================================================
* Generated by somangLee on 2022-01-17
==============================================================*/
$(document).ready(function(){
  
  //header gnb - 1depth
  $('.gnb li a').on('mouseenter', function(){
    $(this).parent('li').addClass('active').siblings('li').removeClass('active');
  });

  // alarm-toggle
  $('.header-side .alarm-toggle').click(function(){
    $(this).parents('li').toggleClass('open');
  });

  // Close the panel when you click the outside area
  $(document).mouseup(function (e){
    var li_open = $('.header-side').find('li.open');
    if(li_open.has(e.target).length === 0){
      li_open.removeClass('open');
    }
  });
});