/*==============================================================
* Generated by somangLee on 2022-01-17
==============================================================*/
$(document).ready(function(){

  //header-active
  $('body').addClass('header-active');
  $('.gnb li a').on('focusout mouseleave', function(e){
    $('body').addClass('header-active');
    e.preventDefault();
  });
    
  // graph width transition 
  $('.general-page .graph-wrap .bar-track .bar').each(function() {
    var dataWidth = $(this).data('value');
    $(this).css("width", dataWidth + "%");
 });

  //download-box-area add class
  $('.download-box-area .download-btn').click(function(){
    $(this).parents('li').toggleClass('active').siblings('li').removeClass('active');
  });
});
